// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAFtTbCOtaRmepRutWup3q8x0Ye5vrFLI',
    appId: '1:103324730349:web:b76e135a4a5673d1bc1de4',
    messagingSenderId: '103324730349',
    projectId: 'apl-appen-aa472',
    authDomain: 'apl-appen-aa472.firebaseapp.com',
    storageBucket: 'apl-appen-aa472.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClELJgKkXJWbD32yDxHrP0iMw8nNilcM8',
    appId: '1:103324730349:android:c8465b86143f8a50bc1de4',
    messagingSenderId: '103324730349',
    projectId: 'apl-appen-aa472',
    storageBucket: 'apl-appen-aa472.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI9MgXU76Bw8joACjFBbsw6OT7G-pv1Og',
    appId: '1:103324730349:ios:af19d39566c26581bc1de4',
    messagingSenderId: '103324730349',
    projectId: 'apl-appen-aa472',
    storageBucket: 'apl-appen-aa472.firebasestorage.app',
    iosBundleId: 'com.example.aplAppen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI9MgXU76Bw8joACjFBbsw6OT7G-pv1Og',
    appId: '1:103324730349:ios:af19d39566c26581bc1de4',
    messagingSenderId: '103324730349',
    projectId: 'apl-appen-aa472',
    storageBucket: 'apl-appen-aa472.firebasestorage.app',
    iosBundleId: 'com.example.aplAppen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAFtTbCOtaRmepRutWup3q8x0Ye5vrFLI',
    appId: '1:103324730349:web:27ad891d99687b62bc1de4',
    messagingSenderId: '103324730349',
    projectId: 'apl-appen-aa472',
    authDomain: 'apl-appen-aa472.firebaseapp.com',
    storageBucket: 'apl-appen-aa472.firebasestorage.app',
  );
}
